spring:
  datasource:
    url: jdbc:h2:file:./data/gtd;MODE=LEGACY
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

server:
  port : 8013